name: Luet repo publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install and Build 🔧
        run: |
          curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
          sudo -E make build-repo create-repo
      - name: Deploy GH Pages 🚀
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          SINGLE_COMMIT: true